name: 04 - Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actions/react-app
    steps:

    #Checks out the code using actions/checkout v5

      - name: Checkout Code
        uses: actions/checkout@v5
    
    #Setups node using v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

    #Installs dependencies which point to file location - 04-using-actions/react-app

      - name: Install Dependencies
        run: npm ci

    #Run unit tests
      
      - name: Run Unit Tests
        run: npm run test