name: 04 - Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    #Checks out the code using actions/checkout v5

      - name: Checkout Code
        uses: actions/checkout@v5
    
    #Setups node using v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: files
        run: |
          ls -al
          cd 04-using-actions
          ls -al
    #Installs dependencies which point to file location - 04-using-actions/react-app

 #     - name: Install Dependencies
  #      run: npm ci
        #working-directory: /github-actions-course/04-using-actions/react-app