name: 07 - Using Expressions

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: jobrun
        default: false
        type: boolean
jobs: 
  echo: 
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] Print start-up data'
        if: ${{ inputs.debug }} == 'true'
        run: echo "working"

    
