name: 12 - Working with Outputs

on: 
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success
        description: "Build Status Choice"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.build.outputs.status }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "$GITHUB_OUTPUT"

      - name: Build
        id: build
        run: echo "status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT

  deploy: 
    if: "${{ jobs.build }} && ${{ inputs.options }} == success"
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploying"
