name: 16 - Working with Environments

on:
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging

    env:  
      my-env-value: "${{ vars.MY_ENV_VALUE || 'default value' }}"
    steps:
      - name: Echo vars
        run: |
          echo "Deploying to staging"
  
  e2e-tests:
    runs-on: ubuntu-latest
    if: ${{ jobs.deploystaging }}

    steps:
      - name: E2E tests
        run: |
          echo "Running E2E"