name: 17 - 1 - Custom Actions - Composite

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: choice
        description: Environment Selection
        options:
          - dev
          - prod

run-name: 17 - 1 - Custom Actions - Composite | env - ${{ inputs.target-env }}

env:
  working-directory: 17-custom-actions/react-app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node and NPM Dependencies
        uses: ./.github/actions/composite-cache-deps
        with: 
          node-version: ${{ inputs.node-version }}
          working-dir: ${{ env.working-directory }}
          target-env: ${{ inputs.target-env }}
      
      - name: Test
        run: |
          npm run test
      
      - name: Build 
        run: |
          npm run build
